version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - "63751:3306"
    volumes:
      - /var/lib/mysql/:/var/lib/mysql/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - backend

  camunda:
    depends_on:
      - db
    image: camunda/camunda-bpm-platform:7.7.0
    ports:
      - "9090:8080"
    volumes:
      - ./camunda/conf/server.xml:/camunda/conf/server.xml
    restart: always
    environment:
      DB_DRIVER: com.mysql.jdbc.Driver
      DB_URL: "jdbc:mysql://db:3306/camunda_local?useUnicode=true&amp;characterEncoding=UTF-8"
      DB_USERNAME: root
      DB_PASSWORD: 123456
      WAIT_FOR: "db:3306"
      TZ: Asia/ShangHai
    networks:
      - backend

networks:
  backend:
